"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { useSearchParams, useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/client";
const schema=z.object({email:z.string().email("Enter a valid email"),password:z.string().min(6,"Password must be at least 6 characters")});type Form=z.infer<typeof schema>;
export function LoginForm(){const router=useRouter();const query=useSearchParams();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(schema)});const submit=async(values:Form)=>{try{const {error}=await createClient().auth.signInWithPassword(values);if(error)throw error;toast.success("Welcome back");router.replace(query.get("next")||"/dashboard");router.refresh()}catch(error){toast.error("Couldn’t sign in",{description:error instanceof Error?error.message:"Please try again."})}};return <main className="grid min-h-screen bg-[#f9f6f1] lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-ink p-12 text-white lg:block"><div className="absolute inset-0 subtle-grid opacity-20"/><div className="absolute -left-10 bottom-0 h-96 w-96 rounded-full bg-champagne/25 blur-3xl"/><div className="relative flex h-full flex-col"><Brand light/><div className="my-auto max-w-md"><p className="eyebrow text-[#e2c399]">A considered studio workspace</p><h1 className="mt-4 font-display text-6xl leading-[.98]">For every story worth remembering.</h1><p className="mt-6 text-base leading-7 text-white/65">RFM keeps the delicate details of each celebration beautifully in motion.</p></div><p className="text-xs text-white/40">© 2026 RFM Wedding Photography</p></div></section><section className="grid place-items-center p-6"><div className="w-full max-w-sm"><div className="lg:hidden"><Brand/></div><div className="mt-12 lg:mt-0"><p className="eyebrow">Welcome back</p><h2 className="mt-2 font-display text-4xl">Sign in to RFM</h2><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Your studio and client spaces, all in one place.</p></div><form onSubmit={handleSubmit(submit)} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-sm font-semibold">Email address</span><Input type="email" placeholder="you@rfmweddings.com" {...register("email")}/>{errors.email&&<p className="mt-1 text-xs text-red-500">{errors.email.message}</p>}</label><label className="block"><span className="mb-2 block text-sm font-semibold">Password</span><Input type="password" placeholder="••••••••" {...register("password")}/>{errors.password&&<p className="mt-1 text-xs text-red-500">{errors.password.message}</p>}</label><Button className="w-full" size="lg" disabled={isSubmitting}>{isSubmitting?"Signing in...":"Sign in"}<ArrowRight size={16}/></Button></form><p className="mt-6 flex items-center justify-center gap-1.5 text-xs text-[hsl(var(--muted-foreground))]"><LockKeyhole size={13}/>Your information is securely protected.</p></div></section></main>}
